# PySNMP SMI module. Autogenerated from smidump -f python ACCEDIAN-SMI
# by libsmi2pysnmp-0.1.3 at Mon Dec  7 10:26:05 2015,
# Python version sys.version_info(major=2, minor=7, micro=9, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( Bits, Integer32, ModuleIdentity, MibIdentifier, ObjectIdentity, TimeTicks, enterprises, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "ObjectIdentity", "TimeTicks", "enterprises")

# Objects

accedianMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 22420)).setRevisions(("2006-08-06 01:00",))
if mibBuilder.loadTexts: accedianMIB.setOrganization("Accedian Networks, Inc.")
if mibBuilder.loadTexts: accedianMIB.setContactInfo("Accedian Technical Assistance Center\nAccedian Networks, Inc.\n4878 Levy, suite 202\nSaint-Laurent, Quebec Canada H4R 2P1\nE-mail: support@accedian.com")
if mibBuilder.loadTexts: accedianMIB.setDescription("The Structure of Management Information for Accedian Networks.")
acdProducts = ObjectIdentity((1, 3, 6, 1, 4, 1, 22420, 1))
if mibBuilder.loadTexts: acdProducts.setDescription("The root of Accedian's Product OIDs.")
acdMibs = ObjectIdentity((1, 3, 6, 1, 4, 1, 22420, 2))
if mibBuilder.loadTexts: acdMibs.setDescription("The root of Accedian's MIB objects.")
acdTraps = ObjectIdentity((1, 3, 6, 1, 4, 1, 22420, 3))
if mibBuilder.loadTexts: acdTraps.setDescription("The root of Accedian's Trap OIDs.")
acdExperiment = MibIdentifier((1, 3, 6, 1, 4, 1, 22420, 4))
acdServices = ObjectIdentity((1, 3, 6, 1, 4, 1, 22420, 5))
if mibBuilder.loadTexts: acdServices.setDescription("The root of Accedian's Services OIDs.")

# Augmentions

# Exports

# Module identity
mibBuilder.exportSymbols("ACCEDIAN-SMI", PYSNMP_MODULE_ID=accedianMIB)

# Objects
mibBuilder.exportSymbols("ACCEDIAN-SMI", accedianMIB=accedianMIB, acdProducts=acdProducts, acdMibs=acdMibs, acdTraps=acdTraps, acdExperiment=acdExperiment, acdServices=acdServices)

